<?php

declare(strict_types=1);

namespace Bga\Games\itarenagame;

/**
 * Данные карт событий
 * 
 * Этот файл содержит все данные о картах событий.
 * Карты создаются в БД только при вытаскивании (ленивая загрузка).
 */
class EventCardsData
{
    /**
     * Возвращает массив всех карт событий
     * 
     * @return array Массив карт, где ключ - card_type_arg, значение - данные карты
     */
    public static function getAllCards(): array
    {
        return [
            1 => [
                'card_type' => 'event',
                'card_type_arg' => 1,
                'number_card' => 1,
                'name' => 'Кризис на рынке труда',
                'image_url' => 'img/event_card/1/1.png',
                'power_round' => 1,
                'description' => 'Компании сталкиваются с нехваткой квалифицированных специалистов, и конкуренция за кадры растет',
                'phase' => 'hiring',
                'effect' => ['type' => 'specialist_card_draw_delta', 'amount' => -2],
                'effect_description' => 'Все игроки берут на 2 карты меньше в этом раунде',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            2 => [
                'card_type' => 'event',
                'card_type_arg' => 2,
                'number_card' => 2,
                'name' => 'Кадровая миграция',
                'image_url' => 'img/event_card/4/23.png',
                'power_round' => 4,
                'description' => 'Специалисты массово переходят в новые сферы, оставляя компании без кандидатов',
                'phase' => 'hiring',
                'effect' => null,
                'effect_description' => 'Все игроки могут сделать только 1 найм в этом раунде. Найм карты в этом раунде стоит 2 раза дороже ',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            3 => [
                'card_type' => 'event',
                'card_type_arg' => 3,
                'number_card' => 3,
                'name' => 'Повышение требований к найму',
                'image_url' => 'img/event_card/1/2.png',
                'power_round' => 1,
                'description' => 'Новые стандарты в компании ограничили количество подходящих кандидатов',
                'phase' => 'hiring',
                'effect' => ['type' => 'specialist_card_draw_delta', 'amount' => -2],
                'effect_description' => 'Все игроки берут на 2 карты меньше в этом раунде',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            4 => [
                'card_type' => 'event',
                'card_type_arg' => 4,
                'number_card' => 4,
                'name' => 'Снижение темпов роста',
                'image_url' => 'img/event_card/2/12.png',
                'power_round' => 2,
                'description' => 'Снижение количества открытых позиций заставляет компании проводить меньше собеседований',
                'phase' => 'hiring',
                'effect' => ['type' => 'specialist_card_draw_delta', 'amount' => -2],
                'effect_description' => 'Все игроки берут на 2 карты меньше в этом раунде',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            5 => [
                'card_type' => 'event',
                'card_type_arg' => 5,
                'number_card' => 5,
                'name' => 'Финансовая грамотность',
                'image_url' => 'img/event_card/1/3.png',
                'power_round' => 1,
                'description' => 'Благодаря обучению и труду вас ждет награда и успех',
                'phase' => 'event',
                'effect' => ['type' => 'all_players_badgers_by_paei'],
                'effect_description' => 'Все игроки получают столько Б, сколько символов выпало на кости PAEI',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ], // +
            6 => [
                'card_type' => 'event',
                'card_type_arg' => 6,
                'number_card' => 6,
                'name' => 'Массовая утечка данных',
                'image_url' => 'img/event_card/1/6.png',
                'power_round' => 1,
                'description' => 'Сразу несколько крупных компаний пострадали от кибератаки, расходы на защиту неизбежны',
                'phase' => 'event',
                'effect' => ['type' => 'all_players_badgers_delta', 'amount' => -1],
                'effect_description' => 'Все игроки платят в банк - 1Б',
                'penalty_first' => '-1',
                'penalty_second' => '-1',
                'penalty_third' => '-2',
                'type' => 'конец раунда',
            ], // +(-) подумать что штрафы
            7 => [
                'card_type' => 'event',
                'card_type_arg' => 7,
                'number_card' => 7,
                'name' => 'Опережение плана',
                'image_url' => 'img/event_card/1/4.png',
                'power_round' => 1,
                'description' => 'Хорошая погода  позитивно повлияла на настроение сотрудников и продуктивность выросла',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки получают столько задач в «бэклог» на треке спринта, сколько символов выпало на кости PAEI',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ], // +
            8 => [
                'card_type' => 'event',
                'card_type_arg' => 8,
                'number_card' => 8,
                'name' => 'Повышение зарплат',
                'image_url' => 'img/event_card/5/26.png',
                'power_round' => 5,
                'description' => 'Повсеместный рост зарплат в сфере IT вынуждает компании сократить найм и пересмотреть приоритеты',
                'phase' => 'hiring',
                'effect' => null,
                'effect_description' => 'За каждую нанятую карту игроки теряют 1 ПО (Рекомендуется в этом раунде делать найм в порядке очередности хода игроков)',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            9 => [
                'card_type' => 'event',
                'card_type_arg' => 9,
                'number_card' => 9,
                'name' => 'Реорганизация рынка труда',
                'image_url' => 'img/event_card/3/18.png',
                'power_round' => 3,
                'description' => 'Перемены в индустрии снизили приток кандидатов',
                'phase' => 'hiring',
                'effect' => null,
                'effect_description' => 'Все игроки делают на 1 найм меньше в этом раунде',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'найм',
            ], // +
            10 => [
                'card_type' => 'event',
                'card_type_arg' => 10,
                'number_card' => 10,
                'name' => 'Охота за профи',
                'image_url' => 'img/event_card/3/16.png',
                'power_round' => 3,
                'description' => 'Компании активно переманивают ценных сотрудников друг у друга',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 2 карты с руки, иначе разыграйте карту события силой 4',
                'penalty_first' => 'not',
                'penalty_second' => '-1',
                'penalty_third' => '-1',
                'type' => 'события',
            ], // +(-) подумать что штрафы
            11 => [
                'card_type' => 'event',
                'card_type_arg' => 11,
                'number_card' => 11,
                'name' => 'Кадровые сокращения',
                'image_url' => 'img/event_card/2/8.png',
                'power_round' => 2,
                'description' => 'Компании массово пересматривают свои структуры, сокращая часть сотрудников из-за изменений на рынке',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки увольняют 1 сотрудника S из своего офиса (Кроме основателя)*',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            12 => [
                'card_type' => 'event',
                'card_type_arg' => 12,
                'number_card' => 12,
                'name' => 'Автоматизация процессов',
                'image_url' => 'img/event_card/5/29.png',
                'power_round' => 5,
                'description' => 'Повсеместное внедрение автоматизации сокращает потребность в персонале',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки увольняют сотрудников F из своего офиса. (Уменьшают производство того трека, какой на перке сотрудника)*',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            13 => [
                'card_type' => 'event',
                'card_type_arg' => 13,
                'number_card' => 13,
                'name' => 'Смена приоритетов',
                'image_url' => 'img/event_card/4/22.png',
                'power_round' => 4,
                'description' => 'Рынок меняется и компании вынужденны подстраиваться, направляя вектор задач в другое русло',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 3 ресурса ( иконки задача смена этапа монета карта), иначе разыграйте карту события силой 5',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            14 => [
                'card_type' => 'event',
                'card_type_arg' => 14,
                'number_card' => 14,
                'name' => 'Технический коллапси',
                'image_url' => 'img/event_card/6/35.png',
                'power_round' => 6,
                'description' => 'Внезапный сбой накрыл все системы, что привело к финансовым потерям компаний',
                'phase' => 'projects',
                'effect' => null,
                'effect_description' => 'Все игроки платят 2Б, за каждый свой IT проект. Иначе получите штраф ПО равный вашему количеству жетонов IT проектов',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            15 => [
                'card_type' => 'event',
                'card_type_arg' => 15,
                'number_card' => 15,
                'name' => 'Проблемы с координацией',
                'image_url' => 'img/event_card/5/28.png',
                'power_round' => 5,
                'description' => 'Нарушения в работе систем планирования заставляют компании временно отложить часть задач',
                'phase' => 'sprint',
                'effect' => null,
                'effect_description' => 'Все игроки убирают задачи с панели спринта:',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            16 => [
                'card_type' => 'event',
                'card_type_arg' => 16,
                'number_card' => 16,
                'name' => 'Рецессия на рынке технологий',
                'image_url' => 'img/event_card/5/25.png',
                'power_round' => 5,
                'description' => 'Спад в экономике заставляет все компании урезать бюджеты и готовиться к трудным временам',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки платят в банк - 10Б',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            17 => [
                'card_type' => 'event',
                'card_type_arg' => 17,
                'number_card' => 17,
                'name' => 'Технологический бум',
                'image_url' => 'img/event_card/6/32.png',
                'power_round' => 6,
                'description' => 'Новые технологии внедряются в рынок, требуя от всех компаний обязательных инвестиций в обновления',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки платят в банк - 16Б',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            18 => [
                'card_type' => 'event',
                'card_type_arg' => 18,
                'number_card' => 18,
                'name' => 'Государственный контроль',
                'image_url' => 'img/event_card/6/33.png',
                'power_round' => 6,
                'description' => 'Новые правила и нормативы требуют от IT-компаний серьезных вложений, чтобы соответствовать установленным стандартам',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки платят 1Б, за каждую карту в своем офисе',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            19 => [
                'card_type' => 'event',
                'card_type_arg' => 19,
                'number_card' => 19,
                'name' => 'Заморозка сделок',
                'image_url' => 'img/event_card/4/19.png',
                'power_round' => 4,
                'description' => 'На время дополнительных проверок приостанавливаются все процессы продаж ',
                'phase' => 'sales',
                'effect' => null,
                'effect_description' => 'Все игроки пропускают фазу «Продажи»',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'продажи',
            ],
            20 => [
                'card_type' => 'event',
                'card_type_arg' => 20,
                'number_card' => 20,
                'name' => 'Перенос дедлайнов',
                'image_url' => 'img/event_card/6/31.png',
                'power_round' => 6,
                'description' => 'Крупный клиент неожиданно перенес сроки, и компании вынуждены временно отложить часть задач',
                'phase' => 'sprint',
                'effect' => null,
                'effect_description' => 'Все игроки убирают задачи с панели спринта:',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            21 => [
                'card_type' => 'event',
                'card_type_arg' => 21,
                'number_card' => 21,
                'name' => 'Крах сети',
                'image_url' => 'img/event_card/2/9.png',
                'power_round' => 2,
                'description' => 'Внезапная поломка парализовала работу компаний, вынуждая их быстро искать решения в условиях цифрового хаоса',
                'phase' => 'skills',
                'effect' => null,
                'effect_description' => 'Все игроки пропускают фазу «Навыки»',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'навыки',
            ],
            22 => [
                'card_type' => 'event',
                'card_type_arg' => 22,
                'number_card' => 22,
                'name' => 'Благотворительность',
                'image_url' => 'img/event_card/4/20.png',
                'power_round' => 4,
                'description' => 'Компания "Проект Гая" обратилась к всем компаниям за помощью в очистке океана.',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут заплатить 1Б чтобы уменьшить свой штраф всего на 1 пункт',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            23 => [ 
                'card_type' => 'event',
                'card_type_arg' => 23,
                'number_card' => 23,
                'name' => 'Сверх продуктивность',
                'image_url' => 'img/event_card/2/10.png',
                'power_round' => 2,
                'description' => 'Благодаря дисциплине, осознанности и спланированному отдыху вы становитесь энергичным и продуктивным.',
                'phase' => 'sprint',
                'effect' => null,
                'effect_description' => 'Все игроки получают столько смен этапа задач на треке спринта, сколько символов выпало на кости PAEI',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            24 => [
                'card_type' => 'event',
                'card_type_arg' => 24,
                'number_card' => 24,
                'name' => 'Популярность IT',
                'image_url' => 'img/event_card/3/15.png',
                'power_round' => 3,
                'description' => 'Код — новая нефть, спрос бьёт все рекорды!',
                'phase' => 'hiring',
                'effect' => null,
                'effect_description' => 'Все игроки получают столько карт, сколько символов выпало на кости PAEI',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            // TODO сдесь добавлю новые
            25 => [
                'card_type' => 'event',
                'card_type_arg' => 25,
                'number_card' => 25,
                'name' => 'Трудности обучения',
                'image_url' => 'img/event_card/1/5.png',
                'power_round' => 1,
                'description' => 'Сотрудникам сложно быстро освоить новые инструменты и процессы, из‑за чего падает скорость выполнения задач',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 1 ресурсу ( иконки задача смена этапа монета карта), иначе разыграйте карту события силой 2',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            26 => [
                'card_type' => 'event',
                'card_type_arg' => 26,
                'number_card' => 26,
                'name' => 'Конфликт в коллективе',
                'image_url' => 'img/event_card/2/11.png',
                'power_round' => 2,
                'description' => 'Ухудшается коммуникация и доверие в команде, снижается продуктивность, растут задержки и риск ухода ключевых сотрудников.',
                'phase' => 'sprint',
                'effect' => null,
                'effect_description' => 'Все игроки убирают 1 задачу с панели спринта',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            27 => [
                'card_type' => 'event',
                'card_type_arg' => 27,
                'number_card' => 27,
                'name' => 'Санкции и блокировки',
                'image_url' => 'img/event_card/3/17.png',
                'power_round' => 3,
                'description' => 'Ограничивается доступ к сервисам, платежам и поставкам, что приводит к вынужденной замене решений, росту издержек и срыву сроков.',
                'phase' => 'sprint',
                'effect' => null,
                'effect_description' => 'Все игроки убирают 2 задачи с панели спринта',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            28 => [
                'card_type' => 'event',
                'card_type_arg' => 28,
                'number_card' => 28,
                'name' => 'Запрет на ключевую технологию',
                'image_url' => 'img/event_card/4/21.png',
                'power_round' => 4,
                'description' => 'Неожиданное решение регулятора запрещает использовать критически важную технологию/платформу. Проекты на ней остановлены до полной переработки или закрыты.',
                'phase' => 'projects',
                'effect' => null,
                'effect_description' => 'Все игроки пропускают фазу «Проекты»',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'проекты',
            ],
            29 => [
                'card_type' => 'event',
                'card_type_arg' => 29,
                'number_card' => 29,
                'name' => 'Внезапная сделка',
                'image_url' => 'img/event_card/5/30.png',
                'power_round' => 5,
                'description' => 'Крупный инвестор неожиданно объявляет о покупке ключевого актива рынка. Сделка меняет баланс сил за один день: долгосрочные стратегии обрываются, незавершённые проекты оцениваются как есть',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => '5-й раунд становится последним в этой партии. 6-й раунд пропускается',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            30 => [
                'card_type' => 'event',
                'card_type_arg' => 30,
                'number_card' => 30,
                'name' => 'Окно возможностей',
                'image_url' => 'img/event_card/16/34.png',
                'power_round' => 6,
                'description' => 'Редкое “окно” на рынке открывается всего на один цикл: игроки могут договориться о совместном выходе/распределении ролей, иначе шанс исчезает и все остаются ни с чем.',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить ресурсы ( иконки задача смена этапа монета карта), иначе разыграйте другую карту события силой 6',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            31 => [
                'card_type' => 'event',
                'card_type_arg' => 31,
                'number_card' => 31,
                'name' => 'Срыв интеграции',
                'image_url' => 'img/event_card/3/13.png',
                'power_round' => 3,
                'description' => 'Новые сервисы плохо стыкуются с текущими системами. Команды тратят время, деньги и силы на исправление ошибок.',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 2 ресурса ( иконки задача смена этапа монета карта), иначе разыграйте карту события силой 4',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'конец раунда',
            ],
            32 => [
                'card_type' => 'event',
                'card_type_arg' => 32,
                'number_card' => 32,
                'name' => 'Аудит процессов',
                'image_url' => 'img/event_card/3/14.png',
                'power_round' => 3,
                'description' => 'В компаниях начинается масштабная проверка внутренних процессов. Часть ресурсов приходится срочно направить на отчёты, исправления и согласования',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 3 ресурса ( иконки задача смена этапа монета карта), иначе разыграйте карту события силой 5',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
            33 => [
                'card_type' => 'event',
                'card_type_arg' => 33,
                'number_card' => 33,
                'name' => 'Перегрузка поддержки',
                'image_url' => 'img/event_card/4/24.png',
                'power_round' => 4,
                'description' => 'После массовых жалоб клиентов службы поддержки не справляются с потоком обращений. Компаниям приходится бросать ресурсы на стабилизацию сервиса и коммуникации.',
                'phase' => 'event',
                'effect' => null,
                'effect_description' => 'Все игроки могут договориться и сбросить по 4 ресурса ( иконки задача смена этапа монета карта), иначе разыграйте карту события силой 6',
                'penalty_first' => 'not',
                'penalty_second' => 'not',
                'penalty_third' => 'not',
                'type' => 'события',
            ],
        ];
    }

    /**
     * Возвращает данные конкретной карты по card_type_arg
     * 
     * @param int $cardTypeArg
     * @return array|null Данные карты или null, если не найдена
     */
    public static function getCard(int $cardTypeArg): ?array
    {
        $cards = self::getAllCards();
        return $cards[$cardTypeArg] ?? null;
    }

    /**
     * Возвращает количество карт каждого типа для создания колоды
     * 
     * @return array Массив для использования в createCards()
     */
    public static function getCardsForDeck(): array
    {
        $result = [];
        foreach (self::getAllCards() as $cardTypeArg => $cardData) {
            $result[] = [
                'type' => $cardData['card_type'],
                'type_arg' => $cardData['card_type_arg'],
                'nbr' => 1, // Количество карт этого типа
            ];
        }
        return $result;
    }
}

